[build]
  publish = "_site"
  command = "eleventy"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    no-cache,
    no-store,
    must-revalidate'''

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'self';"

# From https://www.hawksworx.com/blog/alias-your-mastodon-username-to-your-domain-with-one-netlify-config-setting/
[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://a11y.info/.well-known/webfinger?resource=acct:todd@a11y.info"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
